# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CocoaAsyncSocket', '~> 7.4.3'

  # Pods for SocketTest

end
